#!/usr/bin/env ruby

require 'codeserver'
require 'sinatra'

require 'optparse'

options = CodeServer::SinatraApp::DEFAULT_OPTIONS

OptionParser.new do |opts|
  opts.banner = "Usage: code-server [options]"

  opts.on("-d", "--directory DIRECTORY", "Directory to serve (defaults to .)") do |directory|
    options[:directory] = directory
  end

  opts.on("-b", "--binding BINDING", "Binds to the specified IP (defaults to 0.0.0.0)") do |binding|
    options[:binding] = binding
  end

  opts.on("-p", "--port PORT", "Port number to use (defaults to 4242)") do |port|
    options[:port] = port
  end
end.parse!

CodeServer::SinatraApp.setup!(options)

CodeServer::SinatraApp.run!(root_path: File.expand_path(options[:directory]))

